firstJoin_message: '&9Welcome &a<player> &9to the server!'
join_message: '&7<player> joined'
quit_message: '&7<player> left'
vote_command: 'goldencrates givekey <player> vote'
vote_links:
  - 'https://www.planetminecraft.com/server/simply-survival-4835193/vote/'
  - 'https://minecraft-server-list.com/server/475781/vote/'
  - 'https://minecraft-mp.com/server/283326/vote/'
  - 'https://minecraftservers.org/vote/611637'
help_text:
  - '&6/help: &fShows this text'
  - '&6/menu: &fOpens the server menu'
  - '&6/play: &fJoin the survival world'
  - '&6/spawn: &fGo back to the spawn world'
  - '&6/vote: &fDisplays voting links'
  - '&6/tpa <player>: &FRequest to teleport to someone'
  - '&6/tpaccept: &fAccept a teleport request'
  - '&6/tpdeny: &fDeny a teleport request'
  - '&6/home: &fTeleport to your home'
  - '&6/sethome: &fSets the location of your home'
  - '&6/wild: &fTeleport somewhere random'
ranks:
  owner:
    prefix: '&0[&4Owner&0] '
    perms: []
  admin:
    prefix: '&8[&cAdmin&8] '
    perms:
      - 'goldencrates.admin'
      - 'litebans.*'
      - 'litebans.admin'
      - 'litebans.broadcast'
      - 'survival.vanish'
      - 'survival.modifyspawn'
      - 'survival.serverinfo'
      - 'survival.reloadconfig'
      - 'griefprevention.restorenature'
      - 'griefprevention.restorenatureaggressive'
      - 'griefprevention.adminclaims'
      - 'griefprevention.ignoreclaims'
      - 'griefprevention.deleteclaims'
      - 'griefprevention.adjustclaimblocks'
      - 'griefprevention.eavesdrop'
      - 'griefprevention.eavesdropsigns'
      - 'griefprevention.spam'
      - 'griefprevention.notignorable'
      - 'griefprevention.claimslistother'
      - 'griefprevention.trapped'
      - 'griefprevention.seeclaimsize'
      - 'griefprevention.seeinactivity'
      - 'griefprevention.visualizenearbyclaims'
      - 'griefprevention.transferclaim'
  mod:
    prefix: '&7[&2Mod&7] '
    perms: 
      - 'litebans.*'
      - 'litebans.broadcast'
      - 'survival.vanish'
      - 'griefprevention.eavesdrop'
      - 'griefprevention.eavesdropsigns'
      - 'griefprevention.spam'
      - 'griefprevention.notignorable'
      - 'griefprevention.claimslistother'
      - 'griefprevention.trapped'
      - 'griefprevention.seeclaimsize'
      - 'griefprevention.seeinactivity'
      - 'griefprevention.visualizenearbyclaims'
      - 'griefprevention.transferclaim'
  default:
    prefix: ''
    perms:
      - 'griefprevention.trapped'
      - 'griefprevention.seeclaimsize'
      - 'griefprevention.seeinactivity'
      - 'griefprevention.visualizenearbyclaims'
      - 'griefprevention.transferclaim'